title: Michael Pavkovic's Blog
author: Michael Pavkovic
email: me@michaelpavkovic.com
description: >
  Welcome to my blog! Here, you will find all sorts of
  content ranging from iOS to computers to robotics. Enjoy!
baseurl: ""
url: "https://michaelpavkovic.com"
twitter_username: michaelpavkovic
github_username:  michaelpavkovic
privacy_policy: Privacy Policy
favicon: /favicon.png
resume: /resume

# Give 'pretty' URLs (without the .html at the end)
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Google services
# google_analytics:

# Collections
collections:
  projects:
    output: true
